main:
  - name: About
    url: /
    weight: 10
  - name: Internships
    url: /#internships
    weight: 20
  - name: Education
    url: /#education
    weight: 30
  - name: Publications
    url: /#papers
    weight: 40
